import com.intellij.refactoring.JavaRefactoringSettings;

jrs = JavaRefactoringSettings.getInstance()
jrs.RENAME_SEARCH_IN_COMMENTS_FOR_PACKAGE = false
jrs.RENAME_SEARCH_IN_COMMENTS_FOR_CLASS = false
jrs.RENAME_SEARCH_IN_COMMENTS_FOR_METHOD = false
jrs.RENAME_SEARCH_IN_COMMENTS_FOR_FIELD = false
jrs.RENAME_SEARCH_IN_COMMENTS_FOR_VARIABLE = false
jrs.RENAME_SEARCH_FOR_TEXT_FOR_PACKAGE = false
jrs.RENAME_SEARCH_FOR_TEXT_FOR_CLASS = false
jrs.RENAME_SEARCH_FOR_TEXT_FOR_METHOD = false
jrs.RENAME_SEARCH_FOR_TEXT_FOR_FIELD = false
jrs.RENAME_SEARCH_FOR_TEXT_FOR_VARIABLE = false
jrs.INLINE_CLASS_SEARCH_IN_COMMENTS = false
jrs.INLINE_CLASS_SEARCH_IN_NON_JAVA = false
